CREATE TABLE pageviews (
  id SERIAL PRIMARY KEY,
  view_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  url VARCHAR NOT NULL,
  user_agent VARCHAR NOT NULL,
  referrer VARCHAR NOT NULL,
  device_type SMALLINT NOT NULL DEFAULT '0'
)
